export const CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS'
export const CREATE_ORDER_FAIL = 'CREATE_ORDER_FAIL'
export const GET_MY_ORDERS_SUCCESS = 'GET_MY_ORDERS_SUCCESS'
export const GET_MY_ORDERS_FAIL = 'GET_MY_ORDERS_FAIL'