export const PRODUCTS_DEPARTMENTS_LOAD_SUCCESS = 'PRODUCTS_DEPARTMENTS_LOAD_SUCCESS'
export const PRODUCTS_DEPARTMENTS_LOAD_FAIL = 'PRODUCTS_DEPARTMENTS_LOAD_FAIL'

export const SAVE_PRODUCT_SUCCESS = 'SAVE_PRODUCT_SUCCESS'
export const SAVE_PRODUCT_FAIL = 'SAVE_PRODUCT_FAIL'