export const SECTION_LOAD_SUCCESS = 'SECTION_LOAD_SUCCESS'
export const SECTION_LOAD_FAIL = 'SECTION_LOAD_FAIL'

export const OPEN_PRODUCT_QUICK_VIEW = "OPEN_PRODUCT_QUICK_VIEW"
export const CLOSE_PRODUCT_QUICK_VIEW = "CLOSE_PRODUCT_QUICK_VIEW"

export const BRANDS_LOAD_SUCCESS = "BRANDS_LOAD_SUCCESS"
export const BRANDS_LOAD_FAIL = "BRANDS_LOAD_FAIL"

export const BANNER_LOAD_SUCCESS = "BANNER_LOAD_SUCCESS"
export const BANNER_LOAD_FAIL = "BANNER_LOAD_FAIL"

export const MAIN_CAROUSEL_LOAD_SUCCESS = "MAIN_CAROUSEL_LOAD_SUCCESS"
export const MAIN_CAROUSEL_LOAD_FAIL = "MAIN_CAROUSEL_LOAD_FAIL"